@host = localhost:3001

###

GET http://{{host}}

###

GET http://{{host}}/health-check
Authorization: Hola


###
GET http://{{host}}/user

###
GET http://{{host}}/user?age=99&mode=findOne

### default mode=find (findAll)
GET http://{{host}}/user?age=99

###
POST http://{{host}}/user HTTP/1.1
content-type: application/json

{
  "name": "Chrislo3",
  "age": 60
}

###
PATCH http://{{host}}/user?id=1 HTTP/1.1
content-type: application/json

{
  "nameee": "Chrislo",
  "age": 99
}